[project]
name = "lecture-02"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "aziziashabir", email = "113279601+shabirazizi1@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "asteval>=1.0.9",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "httpx2>=2.12.0",
    "pytest>=9.1.1",
]

[project.scripts]
lecture-02 = "lecture_02:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[tool.pytest.ini_options]
pythonpath = "."
filterwarnings = [
    "ignore::DeprecationWarning"
]